<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="TEST" Id="{c9f63f39-ca52-4283-840c-538bd597e0b6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM TEST
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="TEST">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>