<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_TimestampRegistryTest" Id="{dc36b022-c4cc-4e93-ada4-75afce70000f}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_TimestampRegistryTest
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_TimestampRegistryTest">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>