<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FUN_Scale" Id="{0627413e-0710-4cc7-8ad8-c6d4f5ba5cc6}" SpecialFunc="None">
    <Declaration><![CDATA[///**********************************************************************************
///    Scales input value based on interpolation between input and output
///      min and max values                                                                                              
///**********************************************************************************
FUNCTION FUN_Scale : REAL
VAR_INPUT
	///  The input that is to be scaled	 
	fInputValue: REAL;
	/// The minimum allowable input	 
	fInputMin: REAL;
	/// The maximum allowable input	 
	fInputMax: REAL;
	/// The minimum allowable ouput	 
	fOutputMin: REAL;
	/// The maximum allowable ouput	 
	fOutputMax: REAL;
END_VAR
VAR
	fTemp: REAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[fTemp := FUN_Interpolation(fInputValue, fInputMin, fOutputMin, fInputMax, fOutputMax);
FUN_Scale := FUN_Saturation(fTemp, fOutputMin, fOutputMax);]]></ST>
    </Implementation>
    <LineIds Name="FUN_Scale">
      <LineId Id="3" Count="0" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>