<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_ColourSensor" Id="{29a15434-a9a9-42e4-a5ec-6c6b88beed42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_ColourSensor
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	arrColorSensorStatus	AT %I*: ARRAY[0..3] OF BYTE;
	arrColorSensorData		AT %I*: ARRAY[4..11] OF BYTE;
	nChannelStatus			AT %I*: USINT;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_ColourSensor">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>