<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{4d940c54-4155-4073-8351-63edeb64b412}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[
//PRG_CSVRead();
//PRG_CSVWrite();

//Call Programs
PRG_Simulator();
PRG_TimestampRegistry();

PRG_IO_Link_Master();

]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="40" Count="0" />
      <LineId Id="62" Count="1" />
      <LineId Id="85" Count="1" />
      <LineId Id="84" Count="0" />
      <LineId Id="74" Count="0" />
      <LineId Id="79" Count="0" />
      <LineId Id="87" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="92" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>